[package]
name = "BuckyouInterfaceV2"
edition = "legacy"
license = "MIT"
authors = ["Trillionx Dev (b02901070@ntu.edu.tw)"]
published-at = "0x80fe74322a141e1a4de653c7ed7f8341c457fb91c7415347ba5475cda8c40faf"

[dependencies]
# use big_vector to handle massive player data
TypusFramework = { git = "https://github.com/Typus-Lab/typus-framework", rev = "mainnet" }

[addresses]
buckyou_interface_v2 = "0x80fe74322a141e1a4de653c7ed7f8341c457fb91c7415347ba5475cda8c40faf"
